ALTER TABLE site_settings ADD COLUMN IF NOT EXISTS payments_test_mode BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS payment_test_mode BOOLEAN NOT NULL DEFAULT FALSE;
