import { useEffect, useState, type FormEvent } from "react";
import { api, assetUrl } from "../lib/api";
import { useSite } from "../context/SiteContext";

type Experience={hero_image_url:string;profile_image_url:string;results_phrase:string;rights_phrase:string;assistant_enabled:boolean;mail_provider:"smtp"|"brevo";brevo_sender_email:string;brevo_sender_name:string;contact_email:string;public_site_url:string;virtual_enabled:boolean;virtual_fee:number|string;payment_instructions:string;payments_test_mode:boolean;brevoConfigured:boolean};
type Job={id:string;recipient:string;event_type:string;status:string;attempts:number;last_error:string;created_at:string};
export function ExperienceSettings({onDirtyChange}:{onDirtyChange:(dirty:boolean)=>void}){
  const [value,setValue]=useState<Experience|null>(null),[key,setKey]=useState(""),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[jobs,setJobs]=useState<Job[]>([]);
  const {refresh}=useSite();
  const fail=(e:unknown)=>setMessage(e instanceof Error?e.message:"No fue posible completar la operación.");
  const loadJobs=()=>api<Job[]>("/api/admin/mail-jobs").then(setJobs).catch(fail);
  useEffect(()=>{api<Experience>("/api/admin/experience").then(setValue).catch(fail);void loadJobs();},[]);
  useEffect(()=>{onDirtyChange(dirty);const before=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault();};window.addEventListener("beforeunload",before);return()=>{onDirtyChange(false);window.removeEventListener("beforeunload",before);};},[dirty,onDirtyChange]);
  function update<K extends keyof Experience>(name:K,v:Experience[K]){setValue(current=>current?{...current,[name]:v}:current);setDirty(true);}
  async function save(e:FormEvent){e.preventDefault();if(!value)return;setBusy(true);setMessage("");try{const next=await api<Experience>("/api/admin/experience",{method:"PUT",body:JSON.stringify({...value,brevoApiKey:key})});setValue(next);setKey("");setDirty(false);await refresh();setMessage("Configuración guardada. Los cambios ya están disponibles en el sitio.");}catch(err){fail(err);}finally{setBusy(false);}}
  async function upload(file:File,name:"hero_image_url"|"profile_image_url"){setBusy(true);try{const f=new FormData();f.append("file",file);const r=await api<{url:string}>("/api/admin/uploads",{method:"POST",body:f});update(name,r.url);}catch(e){fail(e);}finally{setBusy(false);}}
  async function test(){if(!value)return;setBusy(true);setMessage("");try{const r=await api<{provider:string;messageId:string}>("/api/admin/experience/test-mail",{method:"POST",body:JSON.stringify({recipient:value.contact_email})});setMessage(`Prueba aceptada por ${r.provider}. Revisa la bandeja de entrada y spam de ${value.contact_email}. ID: ${r.messageId}`);await loadJobs();}catch(e){fail(e);}finally{setBusy(false);}}
  if(!value)return <p>{message||"Cargando configuración…"}</p>;
  return <><div className="admin-page-title"><div><span>Experiencia y comunicación</span><h1>Imagen, pagos y Brevo</h1></div></div>{message&&<p role="status" className="admin-message">{message}</p>}<form onSubmit={save} className="experience-form"><section className="admin-panel editor-panel"><h2>Identidad del sitio</h2><div className="form-grid">{(["hero_image_url","profile_image_url"] as const).map((name,i)=><div key={name}><img className="admin-portrait-preview" src={assetUrl(value[name])} alt={i?"Perfil":"Portada"}/><label className="field"><span>{i?"Foto del perfil y sección El abogado":"Foto de portada"}</span><input value={value[name]} onChange={e=>update(name,e.target.value)}/></label><label className="field"><span>Subir nueva imagen</span><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0],name);}}/></label></div>)}</div><label className="field"><span>Frase de resultados</span><input value={value.results_phrase} required maxLength={200} onChange={e=>update("results_phrase",e.target.value)}/></label><label className="field"><span>Frase del perfil</span><input value={value.rights_phrase} required maxLength={200} onChange={e=>update("rights_phrase",e.target.value)}/></label><label className="toggle-line"><input type="checkbox" checked={value.assistant_enabled} onChange={e=>update("assistant_enabled",e.target.checked)}/> Asistente informativo y herramientas WebMCP</label></section>
  <section className="admin-panel editor-panel"><h2>Correos transaccionales</h2><p>Los avisos importantes se guardan en una cola con reintentos. “Enviado” indica que el proveedor aceptó el envío, no garantiza su entrega en la bandeja.</p><div className="form-grid"><label className="field"><span>Proveedor activo</span><select value={value.mail_provider} onChange={e=>update("mail_provider",e.target.value as "brevo"|"smtp")}><option value="brevo">Brevo API</option><option value="smtp">SMTP de Configuración</option></select></label><label className="field"><span>Correo de avisos del administrador</span><input type="email" required value={value.contact_email} onChange={e=>update("contact_email",e.target.value)}/></label><label className="field"><span>Nombre visible del remitente</span><input required value={value.brevo_sender_name} onChange={e=>update("brevo_sender_name",e.target.value)}/></label><label className="field"><span>Remitente autorizado en Brevo</span><input type="email" value={value.brevo_sender_email} onChange={e=>update("brevo_sender_email",e.target.value)}/></label></div><label className="field"><span>Clave API Brevo · {value.brevoConfigured?"guardada y cifrada":"sin configurar"}</span><input type="password" autoComplete="new-password" value={key} placeholder="Dejar vacío para conservar la clave actual" onChange={e=>{setKey(e.target.value);setDirty(true);}}/></label><label className="field"><span>URL pública del frontend para los enlaces de seguimiento</span><input type="url" value={value.public_site_url} placeholder="https://tu-sitio.vercel.app" onChange={e=>update("public_site_url",e.target.value)}/></label><p className="form-hint">Al cambiar de cuenta, autoriza primero el remitente en Brevo y reemplaza su clave. Las preferencias de avisos al cliente, al despacho y los recordatorios están en Configuración.</p><button type="button" className="button button-dark" disabled={busy||dirty||!value.contact_email} onClick={()=>void test()}>Enviar prueba al administrador</button>{dirty&&<small>Guarda los cambios antes de enviar la prueba.</small>}</section>
  <section className="admin-panel editor-panel"><h2>Consultas virtuales y comprobantes</h2><label className="toggle-line"><input type="checkbox" checked={value.virtual_enabled} onChange={e=>update("virtual_enabled",e.target.checked)}/> Habilitar citas virtuales</label><label className="toggle-line"><input type="checkbox" checked={value.payments_test_mode} onChange={e=>update("payments_test_mode",e.target.checked)}/> Modo de prueba · no solicitar transferencias reales</label><label className="field"><span>Valor de la consulta · USD</span><input type="number" min={0} max={100000} step="0.01" value={value.virtual_fee} onChange={e=>update("virtual_fee",e.target.value)}/></label><label className="field"><span>Instrucciones / cuenta bancaria</span><textarea rows={6} maxLength={2500} value={value.payment_instructions} onChange={e=>update("payment_instructions",e.target.value)}/></label><p className="form-hint">Cada cita conserva el importe y las instrucciones vigentes al reservar. Cambiar estos datos no modifica las reservas anteriores. La validación del comprobante es manual; no hay cobros automáticos.</p></section><button className="button button-gold" disabled={busy}>{busy?"Procesando…":"Guardar configuración"}</button></form>
  <section className="admin-panel table-panel"><header><h2>Cola de avisos</h2><button onClick={()=>void loadJobs()}>Actualizar</button></header><div className="admin-table-wrap"><table><thead><tr><th>Destinatario</th><th>Evento</th><th>Estado</th><th>Intentos</th><th>Detalle</th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td>{j.recipient}</td><td>{j.event_type}</td><td>{j.status}</td><td>{j.attempts}</td><td>{j.last_error}{j.status==="failed"&&<button disabled={busy} onClick={async()=>{setBusy(true);try{await api(`/api/admin/mail-jobs/${j.id}/retry`,{method:"POST"});await loadJobs();}catch(e){fail(e);}finally{setBusy(false);}}}>Reintentar</button>}</td></tr>)}</tbody></table>{!jobs.length&&<p className="admin-empty">Los avisos de citas y consultas aparecerán aquí.</p>}</div></section></>;
}
